config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests, :only => [:new, :create] do
    post "approve", on: :member
    post "deny", on: :member
  end

  resources :users, :only => [:new, :create]
  resource :session
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = ["Black", "Brown", "Orange", "White"]
  attr_accessible :name, :age, :birth_date, :color, :sex
  validates :name, :age, :birth_date, :color, :sex, presence: true
  validates :age, numericality: true
  validates :sex, inclusion: { in: %w(M F) }
  validates :color, inclusion: COLORS

  has_many(
    :cat_rental_requests,
    :class_name => 'CatRentalRequest',
    :primary_key => :id,
    :foreign_key => :cat_id,
    :dependent => :destroy
  )

  belongs_to(
    :owner,
    :class_name => 'User',
    :primary_key => :id,
    :foreign_key => :user_id
  )
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUSES = ["APPROVED", "DENIED", "PENDING"]
  
  attr_accessible :cat_id, :end_date, :start_date, :status
  validates :cat_id, :end_date, :start_date, presence: true
  validates :status, inclusion: STATUSES
  before_validation :assign_pending_status
  #validate

  belongs_to(
    :cat,
    :class_name => 'Cat',
    :primary_key => :id,
    :foreign_key => :cat_id
  )

  def approve!
    raise "not pending" unless self.status == 'PENDING'
    transaction do
      self.status = 'APPROVED'
      self.save!

      overlapping_pending_requests.each do |request|
        request.status = 'DENIED'
        request.save!
      end
    end
  end

  def deny!
    self.status = 'DENIED'
    self.save!
  end

  def pending?
    self.status == 'PENDING'
  end

  private
  
  def overlapping_requests
    conditions = <<-SQL
      ((cat_id = :cat_id) AND (start_date < :end_date) AND (end_date > :start_date))
    SQL
    overlapping_requests = CatRentalRequest.where(conditions, {
      cat_id: self.cat_id, start_date: self.start_date, end_date: self.end_date
    })

    if self.id.nil?
      overlapping_requests
    else
      overlapping_requests.where("id != ?", self.id)
    end
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

  def assign_pending_status
    self.status ||= 'PENDING'
  end
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
#  include Bcrypt

  attr_accessible :user_name, :password
  validates :user_name, :password_digest, :session_token, presence: true
  validates :user_name, uniqueness: true
  before_validation :require_token

  has_many(
    :cats,
    :class_name => 'Cat',
    :primary_key => :id,
    :foreign_key => :user_id
  )

  def password=(password)
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)

    user.is_password?(password) ? user : nil
  end

  def reset_session_token!(force = true)
    return unless self.session_token.nil? || force

    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
  end

  def is_owner?(cat)
    self.id == cat.owner.id
  end

  private

  def require_token
    self.session_token ||= self.session_token = SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cat_rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cat_rental_request = CatRentalRequest.new(params[:cat_rental_request])
    if @cat_rental_request.save
      @cat = Cat.find_by_id(@cat_rental_request.cat_id)
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def approve
    current_request.approve!
    redirect_to cat_url(current_cat)
  end

  def deny
    current_request.deny!
    redirect_to cat_url(current_cat)
  end

  private

  def current_request
    @cat_rental_request ||= CatRentalRequest.find_by_id(params[:id])
  end

  def current_cat
    @cat ||= current_request.cat
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :require_owner, only: [:edit, :update]

  def index
    @cats = Cat.includes(:owner).all
    render :index
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(params[:cat])
    @cat.user_id = current_user.id

    if @cat.save
      render :show
    else
      render :new
    end
  end

  def show
    @cat = current_cat
    render :show
  end

  def edit
    @cat = current_cat
    render :edit    
  end

  def update
    current_cat.update_attributes!(params[:cat])
    redirect_to cat_url(current_cat)
    #render :show
  end

  private

  def current_cat
    @current_cat ||= Cat.includes(:owner).find(params[:id])
  end

  def require_owner
    redirect_to cat_url(current_cat) unless current_user.is_owner?(current_cat)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:user_name], params[:user][:password])
    if user.nil?
      render :new
    else
      login_user!(user)
      redirect_to cats_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login_user!(@user)
      redirect_to cats_url
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Create Rental Request</h1>

<form action="<%= cat_rental_requests_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="cat_rental_request_cat_id">Cat</label>
  <select name="cat_rental_request[cat_id]" id="cat_rental_request_cat_id">
    <option></option>
    <% Cat.all.each do |cat| %>
      <option 
       value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <br>

  <label for="cat_rental_request_start_date">Start Date</label>
  <input
    type="date"
    name="cat_rental_request[start_date]"
    id="cat_rental_request_start_date">
  <br>

  <label for="cat_rental_request_end_date">End Date</label>
  <input
    type="date"
    name="cat_rental_request[end_date]"
    id="cat_rental_request_end_date">
  <br>

  <input type="submit">
</form>

app/views/cats/edit.html.erb
<%= render 'shared/form', cat: @cat %>

app/views/cats/index.html.erb
<br />
<br />
<table>
<tr>
  <th>Name</th>
  <th>Age</th>
  <th>Sex</th>
  <th>Color</th>
  <th>Birth date</th>
  <th>Owner</th>
</tr>
<% @cats.each do |cat| %>
  <tr>
    <td><%= link_to cat.name, cat_url(cat) %></td>
    <td><%= cat.age %></td>
    <td><%= cat.sex %></td>
    <td><%= cat.color %></td>
    <td><%= cat.birth_date %></td>
    <td><%= cat.owner.user_name %></td>
  </tr>
<% end %>
</table>

app/views/cats/new.html.erb
<%= render 'shared/form', cat: @cat %>

app/views/cats/show.html.erb
<h1>Cat: <%= @cat.name %></h1>
<%= link_to 'Edit', edit_cat_url(@cat) if current_user.is_owner?(@cat) %>
<ul>
  <li>Age: <%= @cat.age %></li>
  <li>Sex: <%= @cat.sex %></li>
  <li>Color: <%= @cat.color %></li>
  <li>Birth date: <%= @cat.birth_date %></li>
  <li>Owner: <%= @cat.owner.user_name %></li>
</ul>
<br>
<hr>
<h1>Existing requests</h1>
<%= link_to 'Reserve cat', new_cat_rental_request_url %>
<ul>
  <% @cat.cat_rental_requests.order("start_date").each do |request| %>
    <li><%= "#{request.start_date} – #{request.end_date}" %></li>
    <% if request.pending? && current_user.is_owner?(@cat) %>
      <%= button_to "Approve", approve_cat_rental_request_url(request) %>
      <%= button_to "Decline", deny_cat_rental_request_url(request) %>
    <% else %>
      <%= request.status %>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top_nav">
  <%= link_to "Register cat", new_cat_url %> | 
  <%= link_to "All cats", cats_url %> | 
  <%= link_to "Reserve cats", new_cat_rental_request_url %> 
  <% if current_user.nil? %>
    (<%= link_to "Sign up", new_user_url %> | 
    <%= link_to "Log in", new_session_url %>)
  <% else %>
    Welcome, <%= current_user.user_name %>! 
    (<%= link_to "Log out", session_url, method: "delete" %>)
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/shared/_form.html.erb
<% subject = (cat.persisted? ? "Edit" : "Register") %>
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :put : :post) %>
<h1><%= subject %> cat</h1>
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="cat_name">Name</label>
  <input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>">
  <br>

  <label for="cat_age">Age</label>
  <input
    type="number"
    name="cat[age]"
    id="cat_age"
    value="<%= cat.age %>">
  <br>

  <label for="cat_birth_date">Birth date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="cat_birth_date"
    value="<%= cat.birth_date %>">
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option></option>
    <% Cat::COLORS.each do |color| %>
      <option
        <%= cat.color == color ? "selected" : "" %>
        value="<%= color %>">
        <%= color.upcase %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">Male</label>
  <input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_female">Female</label>
  <br>
  <br>
  <input type="submit" value="Register cat">
</form>

app/views/users/new.html.erb
<h1>Sign up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="user_user_name">Username</label>
  <input type="text" name="user[user_name]" id="user_user_name"></input>
  <br />
  <label for="user_user_password">Password</label>
  <input type="password" name="user[password]" id="user_password"></input>
  <br />
  <input type="submit" value="Register">
</form>